// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOy79Yw1r7mCX68Tr7MfdJ0krzSsOBuSU',
    appId: '1:26029076554:web:538b113f70448ea4fcb6b3',
    messagingSenderId: '26029076554',
    projectId: 'himfo-app-f52b3',
    authDomain: 'himfo-app-f52b3.firebaseapp.com',
    storageBucket: 'himfo-app-f52b3.firebasestorage.app',
    measurementId: 'G-TNM99W9F4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO21s9M79ujJaJzv4Zk4y21dliBfjGd6o',
    appId: '1:26029076554:android:15a07af137cb61cbfcb6b3',
    messagingSenderId: '26029076554',
    projectId: 'himfo-app-f52b3',
    storageBucket: 'himfo-app-f52b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWkALM6EakSyyBoDJ2LOgdlll_HDDEz8',
    appId: '1:26029076554:ios:12851791696cb515fcb6b3',
    messagingSenderId: '26029076554',
    projectId: 'himfo-app-f52b3',
    storageBucket: 'himfo-app-f52b3.firebasestorage.app',
    iosBundleId: 'com.example.himtikaMobileInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWkALM6EakSyyBoDJ2LOgdlll_HDDEz8',
    appId: '1:26029076554:ios:12851791696cb515fcb6b3',
    messagingSenderId: '26029076554',
    projectId: 'himfo-app-f52b3',
    storageBucket: 'himfo-app-f52b3.firebasestorage.app',
    iosBundleId: 'com.example.himtikaMobileInformation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOy79Yw1r7mCX68Tr7MfdJ0krzSsOBuSU',
    appId: '1:26029076554:web:80126b5832c57687fcb6b3',
    messagingSenderId: '26029076554',
    projectId: 'himfo-app-f52b3',
    authDomain: 'himfo-app-f52b3.firebaseapp.com',
    storageBucket: 'himfo-app-f52b3.firebasestorage.app',
    measurementId: 'G-WF5B565L1L',
  );
}
